---
- name: Print env variable
  shell: printenv
  register: print_result

- name: Execute DB migrations and save the result to Memstash.io
  become: true
  shell: |
      cd /home/ubuntu/backend
      ls
      npm run migrations > migrations.txt
      cat migrations.txt

- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "remove dependencies that are no longer required"
  become: yes
  apt:
    autoremove: yes

- name: "install nodejs and npm"
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present