- name: Creates directory
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Transfer backend files cloud server
  copy:
    src: /root/project/backend/dist
    dest: /home/ubuntu/backend

- name: "Update npm"
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm install -g npm@latest
    
- name: Executing node
  become: true
  shell: |
    cd /home/ubuntu/backend/
    pm2 start -f ./main.js
    pm2 ls