- name: Creates directory
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Transfer backend files cloud server
  copy:
    src: ../../backend/dist
    dest: /home/ubuntu/udabackend

- name: "Update npm"
  become: true
  shell: |
    cd /home/ubuntu/udabackend
    npm install -g npm@latest
    
- name: "install package dependencies"
  become: true
  shell: |
    cd /home/ubuntu/backend   
    ls -la
    npm install
    
- name: Executing node
  become: true
  shell: |
    cd /home/ubuntu/udabackend
    pm2 start -f ./main.js
    pm2 ls